# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Ablaze.Floorp
PackageVersion: 12.17.2@155.0
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2026-09-03
Scope: machine
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
ElevationRequirement: elevatesRequired
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v12.17.2/floorp-windows-x86_64.installer.exe
  InstallerSha256: CA793B08A00DF91BD027261092501084B42BD97745BD3E53BDFC3DD5C694B441
ProductCode: Ablaze Floorp
ManifestType: installer
ManifestVersion: 1.12.0
