# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Ablaze.Floorp
PackageVersion: 11.11.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Commands:
- floorp
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
ReleaseDate: 2024-03-25
Scope: machine
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v11.11.2/floorp-win64.installer.exe
  InstallerSha256: 6816C78240BEB19EABC6E3980040133C0D4F53470D8EBAA10E28E9DE550A26BA
- Architecture: x86
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v11.11.2/floorp-win32.installer.exe
  InstallerSha256: 5AA1716C4347FA1817CE6163F8BE05A7CB036EAC9B49D16A28BEE5D7508CACF7
ManifestType: installer
ManifestVersion: 1.6.0
