# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json
PackageIdentifier: Ablaze.Floorp.Daylight
PackageVersion: 11.8.1
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/beta/floorp-win64.installer.exe
  InstallerSha256: 5E571DB2930153F4BEED0898EF6B427AF88063FB6F5595ECEA61FF029361A06C
ManifestType: installer
ManifestVersion: 1.5.0
