# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json
PackageIdentifier: Ablaze.Floorp
PackageVersion: 11.8.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Commands:
- floorp
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
ReleaseDate: 2024-01-17
Scope: machine
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v11.8.1/floorp-win64.installer.exe
  InstallerSha256: 01BF104EEBCD059B6A7A44CFE27BF35DAA0F42B45C3E9A4A5C003FD415910876
- Architecture: x86
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v11.8.1/floorp-win32.installer.exe
  InstallerSha256: 58048B1463A12AC9C1760D9E2B380B0E5ACA0328B3EFF60CD7F5368E6E03291E
ManifestType: installer
ManifestVersion: 1.5.0
