# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json
PackageIdentifier: Ablaze.Floorp
PackageVersion: 11.9.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Commands:
- floorp
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
ReleaseDate: 2024-02-02
Scope: machine
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v11.9.0/floorp-win64.installer.exe
  InstallerSha256: 33A21F2A1CAF2C45AB13CEC90AAE969606852E3AD9DC4A3844CB6A7CB5DAA820
- Architecture: x86
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v11.9.0/floorp-win32.installer.exe
  InstallerSha256: 137C98C2A6D67395C96D36897A37FF83E1DF330BF03A90875824B1F84E4CE700
ManifestType: installer
ManifestVersion: 1.5.0
