# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Ablaze.Floorp
PackageVersion: 11.17.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Commands:
- floorp
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
ReleaseDate: 2024-08-16
Scope: machine
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v11.17.0/floorp-win64.installer.exe
  InstallerSha256: 98C95F75DB2C713C9183CD4B03820A72713676F85B0C1C1052C809BA877DBC58
ManifestType: installer
ManifestVersion: 1.6.0
