# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: Ablaze.Floorp.Daylight
PackageVersion: 136.0.3@0.1.21
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Scope: machine
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Floorp-Projects/Floorp-12/releases/download/beta/floorp-win64-installer.exe
  InstallerSha256: 420CF9F8331B8CC41E3FA737A3E4699F90F1A9E84FD34D88F5DF95B95E387F1D
  AppsAndFeaturesEntries:
  - DisplayName: Floorp Daylight (x64 en-US)
    ProductCode: Floorp Daylight 136.0.3@0.1.21 (x64 en-US)
ManifestType: installer
ManifestVersion: 1.9.0
