# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.5.0.schema.json
PackageIdentifier: Ablaze.Floorp
PackageVersion: 11.3.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Commands:
- floorp
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
ReleaseDate: 2023-09-07
Installers:
- Architecture: x64
  Scope: machine
  InstallerLocale: en-US
  InstallerType: nullsoft
  InstallModes:
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v11.3.0/floorp-win64.installer.exe
  InstallerSha256: ABA80EAEFC81BACDBD126B66037682FCB5F9000A959D5D7E8E558E622A38E179
ManifestType: installer
ManifestVersion: 1.5.0