# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json
PackageIdentifier: Ablaze.Floorp
PackageVersion: 11.8.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Commands:
- floorp
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
ReleaseDate: 2024-01-17
Scope: machine
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v11.8.0/floorp-win64.installer.exe
  InstallerSha256: 6B68EC6C0AD8E3433720581B96291042DDE5D43FD288E4F3F02A4A11EE3405F8
- Architecture: x86
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v11.8.0/floorp-win32.installer.exe
  InstallerSha256: 9E92BA3D5053F89389BBA1FEC21FA5690F669A9562A305539DDCD6575D8BEDFB
ManifestType: installer
ManifestVersion: 1.5.0
